### ISSUE TITLE
Remove Layer Selection functionality from the napari-imagej menu

### ISSUE THREAD

**Issue by gselzer** [imagej/napari-imagej#102]
napari-imagej provides buttons in its button menu for transferring data to and from an ImageJ2 GUI. These buttons can perform one of two actions, where the chosen action is defined via the `choose_active_layer` setting:
1. Choose the active layer in napari and transfer it over to the ImageJ2 GUI, or the active window in the ImageJ2 GUI and transfer that data over to napari.
2. Provide the user with a dialog box, prompting the selection of a layer from a drop-down list of all existing layers. The selection is what is transferred between the applications.

@ctrueden [said](https://github.com/imagej/napari-imagej/pull/99#discussion_r964127804):
> Not really specific to this PR, but... has anyone actually asked for the ability to explicitly select the layer, rather than having it always be the active one? If not, I'd favor removing this feature in favor of always using the active layer. And programmatically, still allowing the layer to be specified in code. Having this option makes testing more complex, and I'm not convinced anyone will want to change this setting.

Here are my thoughts:
* I personally prefer using the active layer, over choosing.
* I hesitate to remove functionality that already exists. I know that Git history would make it easy to recover that functionality if we decide later that it is beneficial, but I also tend to think "if it ain't broke, don't fix it". But, at the same time, simplicity is nice, and I think now is the time to remove it if we are going to.
* I pestered @elevans to get his opinion, and he asked me what napari's convention is for selecting a layer. Being rather out of the loop, I tend to think that it *is providing that dropdown*, since that is what you'd be provided if you wrapped a function asking for a `Layer` to `magicgui`. Do you have any opinions on this @tlambert03?
*  Here's one situation where I might want to use the chosen layer: it might be easier to select a layer when my napari viewer contains a lot of layers (think dozens). Instead of scrolling through the list to find the one I want, it might be faster to bring up the dropdown and use keystrokes to quickly identify the layer I want. I don't think this is a particularly compelling use case, though...

Happy to hear thoughts, as my default position is to leave it in.

**Comment by gselzer** [comment]
@ctrueden suggests:

> small usability thing: I get confused about "choose active layer" because to me that sounds like a thing I should have checked when I want to choose which layer will be sent back and forth, whereas in practice it has to be unchecked for me to get a choice.

If we're going to keep this functionality, we can rename it. @ctrueden do you have naming suggestions?

**Comment by ctrueden** [comment]
There is enough disagreement with my position (that we should just always use the active layer, and not provide an option otherwise) that I'm going to close this. I did push a commit renaming `choose_active_layer` to `use_active_layer`, which I find less confusing.
