### ISSUE TITLE
Add a setting for the scripts source directory

### ISSUE THREAD

**Issue by gselzer** [imagej/napari-imagej#104]
Now that we have better configuration, let's throw the scripts subdirectory in as an option.
TODO:
* Add the scripts subdirectory as a setting
* Make the settings dialog in the GUI register that setting as a path (i.e. pop up the file chooser)
* Fix the documentation
* Consider testing it...somehow

**Comment by ctrueden** [comment]
As discussed, let's call it "ImageJ base directory" since that directory is also used for discovering lookup tables (in `luts/`) and additional plugins (in `plugins/`) and macros (in `macros/`).
