### ISSUE TITLE
Clearing the search bar still yields script template results

### ISSUE THREAD

**Issue by ctrueden** [imagej/napari-imagej#113]
Type a search string, then delete what you typed. There will still be results in the results box, specifically Script templates:

<img width="322" alt="empty-search-string" src="https://user-images.githubusercontent.com/556626/193888103-f2fc0e0f-cca4-4e75-945a-1f5860a25f54.png">

**Comment by gselzer** [comment]
This seems to be a problem with the Script templates `Searcher`, @ctrueden; it also happens in Fiji. Where is that `Searcher` located? It'd be best to move this issue there.

**Comment by ctrueden** [comment]
I agree that we should fix it in the script template searcher. But it would also be good to have explicit handling here in napari-imagej to clear the results explicitly whenever the text field gets blanked out.

@gselzer wrote:
> Where is that `Searcher` located?

```python
#@ PluginService ps
from org.scijava.search import Searcher
for searcher in ps.getPluginsOfType(Searcher):
	print(searcher)
```
```
class='org.scijava.search.snippet.SnippetSearcher', priority=1000000.0, enabled=true, pluginType=Searcher
class='org.scijava.search.module.ModuleSearcher', priority=10000.0, enabled=true, pluginType=Searcher
class='net.imagej.ops.search.OpSearcher', priority=9999.0, enabled=true, pluginType=Searcher
class='org.scijava.search.template.TemplateSearcher', priority=9990.0, enabled=true, pluginType=Searcher
class='org.scijava.search.web.ImageJWikiSearcher', priority=100.0, enabled=false, pluginType=Searcher
class='org.scijava.search.classes.ClassesSearcher', priority=0.0, enabled=true, pluginType=Searcher
class='org.scijava.search.web.ImageScSearcher', priority=0.0, enabled=false, pluginType=Searcher
````

**Comment by gselzer** [comment]
> But it would also be good to have explicit handling here in napari-imagej to clear the results explicitly whenever the text field gets blanked out.

I don't think it's that simple @ctrueden. Getting from search text to results is all done through event handlers, and we leave any search ordering up to the `SearchOperation`. Thus if we were to try to process different search texts diffrently (i.e. by handling an empty string search ourselves), we might break the search ordering and see weird behavior.

For example, suppose you start from a fresh terminal, and type `f` and then immediately clear the search bar. If we finish handling the empty string from clearing the bar before the `searchOperation` returns the results from searching `f`, we'll have search results with no search string.

As much as I'd like to handle clearing the search bar ourselves, it would take a lot of yucky refactoring to do so
