### ISSUE TITLE
Ops search results are no longer present

### ISSUE THREAD

**Issue by ctrueden** [imagej/napari-imagej#114]
In the current version of napari-imagej, I'm not seeing any Ops search results, only Commands and Script templates:

<img width="344" alt="no-ops" src="https://user-images.githubusercontent.com/556626/193891520-e895979c-ef9a-4904-b8a3-1f815fb6ef21.png">

The Commands results do have ops mixed in, because ImageJ Ops v1 Op plugins *are* Commands, but they won't work the same as when they are invoked via the OpListing mechanism.

**Comment by gselzer** [comment]
@ctrueden what happens when you run, in the napari console:
```
from imagej import ij; ij.prefs().clearAll();
```
Does that fix the issue?

Just wondering if it is related to the `PrefService` at all.

**Comment by hinerm** [comment]
fwiw I get different results:
![image](https://user-images.githubusercontent.com/1123809/193899170-896c0b5a-4a50-4073-be91-7c2f36dbae0f.png)

**Comment by gselzer** [comment]
@ctrueden had the idea that this may be tied to the checkboxes in fiji; if they become unchecked, categories of `SearchResult`s might become unavailable in napari-imagej.

This seems like it might be the culprit. I was able to reproduce, taking the following steps:
1. Open Fiji
2. Search something, and then uncheck Ops
3. Open napari-imagej
4. Search something, observe no Ops results
5. Open the napari console, and type `from imagej import ij; ij.prefs().clearAll()`
6. Search something, and see that Ops appear again.
