### ISSUE TITLE
Use BSD-2 or MIT or ISC license, not BSD-3

### ISSUE THREAD

**Issue by ctrueden** [imagej/napari-imagej#156]
The BSD-3 license's third clause can create some legal annoyances, and my understanding is (although IANAL) that it is also not necessary legally. To be consistent with the rest of ImageJ2, we should use BSD-2, which is what is used for the permissive license in nearly all other ImageJ2 components (except PyImageJ, which we made Apache 2 for some reason I don't remember).

**Comment by gselzer** [comment]
@ctrueden does napari's license affect our choice here? Does pyimagej's?

**Comment by ctrueden** [comment]
@gselzer Nope, napari and PyImageJ are both permissively licensed, so we do not need to worry about them, other than being compatible and ideally consistent. I guess you chose BSD-3 because napari is BSD-3? But it doesn't matter; napari-imagej can just as well be BSD-2. Since the rest of ImageJ2 is BSD-2, I prefer it over BSD-3. I also prefer simplicity over complexity in the licensing; IMHO BSD-3 is never necessary, and I'm a little surprised napari picked that one.
