### ISSUE TITLE
Allow users to specify their ImageJ distribution

### ISSUE THREAD

**Issue by gselzer** [imagej/napari-imagej#16]
@ctrueden [says](https://github.com/imagej/napari-imagej/issues/14#issuecomment-1085113056) (in #14):

> > I'd much rather create a napari-trackmate plugin or so instead of trying to shoehorn that functionality into this plugin.

> That is fair, and I think I agree. But I do think you should be able to, with napari-imagej and no other napari plugins installed, initialize your ImageJ2 with whatever init string you want (including a locally wrapped ImageJ2 installation if desired). That way, people can invoke Fiji plugins with the search bar, for example—they just won't magically gain additional data structure conversions beyond those fundamentally supported. But for the vast majority of such plugins, they won't need anything extra.

Hmm, how do we add this functionality without it becoming an annoyance? If I just want stock ImageJ would I want to click through a startup screen every time I want to start the plugin? I'd prefer that this was some setting you could specify.

Maybe we could have an "napari-imagej-startup" plugin that allows you to modify where your imagej comes from? :laughing:

**Comment by ctrueden** [comment]
> how do we add this functionality without it becoming an annoyance?

napari needs an options dialog, a la ImageJ2 `OptionsPlugin`s. Then plugins could register typed options displayed in a dialog with components by magicgui.

And until then: next to the search bar we could add a little ⚙ button for bringing up the plugin's options.

**Comment by gselzer** [comment]
@tlambert03 do you have an opinion on this?

**Comment by tlambert03** [comment]
this is in the works.  see https://github.com/napari/npe2/blob/main/npe2/manifest/contributions/_configuration.py ... which allows exactly this... it just hasn't been exposed in the contributions points yet
