### ISSUE TITLE
Enable multiple endpoints from configuration dialog

### ISSUE THREAD

**Issue by gselzer** [imagej/napari-imagej#164]
PyImageJ allows you to [specify plugins in your initialization string](https://pyimagej.readthedocs.io/en/latest/Initialization.html#ways-to-initialize). It would be nice if we could allow this also.

Unfortunately, I have no idea whether `confuse` and/or `magicgui` support `List[String]`, so we'll have to find that out. If they don't, we will need to split the current string setting by a comma, or something.

**Comment by ctrueden** [comment]
The jgo convention currently is to separate multiple endpoints with the plus `+` symbol.

**Comment by gselzer** [comment]
> The jgo convention currently is to separate multiple endpoints with the plus `+` symbol.

Well, that's good to know, thanks!

In that case, it's probably as simple as documenting that this is how you do it in the configuration section of the `README`
