### ISSUE TITLE
Commands have duplicate help/source buttons

### ISSUE THREAD

**Issue by hinerm** [imagej/napari-imagej#178]
![image](https://user-images.githubusercontent.com/1123809/223217900-fe0cbe0f-9789-473f-8352-f6267667f47a.png)

What is the distinction between these buttons? Sometimes the `Source` button goes to the same place (e.g. for `View: AddDimension`) and sometimes it seems to go to separate IJ1/IJ2 sources (`Add Selection...`). The first `Help` button (indicated) seems to want to go to an original ImageJ-style URL and has not worked for me. The second `Help` button works fine for me in the cases I tried.

**Comment by ctrueden** [comment]
I'm guessing it has to do with ImageJ2 `LegacyCommand` wrappers around original ImageJ commands.
The problem also happens when running ImageJ2+ImageJ via `jgo -m net.imagej:imagej:2.10.0+net.imagej:imagej-legacy:MANAGED` (although strangely, it does not occur when running `jgo sc.fiji:fiji:2.10.0`...).

**Comment by gselzer** [comment]
@ctrueden @hinerm this is happening because scijava/scijava-search#24 and scijava/script-editor#63 were merged, and imagej/imagej-legacy#283 was not.

**Comment by gselzer** [comment]
Is it worth fixing this by requiring a minimum imagej legacy version, or should we just leave it as is?

**Comment by hinerm** [comment]
See also https://github.com/scijava/scijava-search/pull/28

**Comment by hinerm** [comment]
@gselzer The legacy links should be fixed once we figure out why there's no [1.54c tag](https://github.com/imagej/ImageJ/tags) from the [action build](https://github.com/imagej/ImageJ/actions/runs/4350574748/jobs/7601413407) - right?

**Comment by hinerm** [comment]
> The legacy links should be fixed once we figure out why there's no [1.54c tag](https://github.com/imagej/ImageJ/tags) from the [action build](https://github.com/imagej/ImageJ/actions/runs/4350574748/jobs/7601413407) - right?

Answer: these were being built manually and `1.54c` simply hadn't been built yet.
