### ISSUE TITLE
Marching cubes output is not aligned

### ISSUE THREAD

**Issue by kephale** [imagej/napari-imagej#198]
Howdy,

I tested the marching cubes op on napari's binary blobs (3D) sample data. The resulting mesh seems to have some flipped axes. 

Relatedly, is it feasible to have some indicator that the ImageJ call is still running? I couldn't figure out if anything actually happened after pressing run [so I button mashed and got a bunch of copies of the surface].

edit:
Another consideration: it seems like at least the name of the layer could be preserved in some way.

<img width="984" alt="image" src="https://user-images.githubusercontent.com/400105/230918748-598e080b-787e-4fb7-81ea-c8a9a0d91e11.png">

**Comment by gselzer** [comment]
Thanks so much @kephale!

> The resulting mesh seems to have some flipped axes.

Yeah, this may be related to #189. I am hoping to look into this soon.

> Relatedly, is it feasible to have some indicator that the ImageJ call is still running?

#55 talks about this. I don't have a great idea yet, but I have been thinking about this too. Ideally, I'd want something that is visible but not too obtrusive, and it would be cool to denote progress if that's supported by the `Module`. What do you think about adding something at the bottom of the napari-imagej widget, where the version is listed?

> it seems like at least the name of the layer could be preserved in some way.

Yeah, that's tricky. `imagej-mesh` [`Mesh`](https://github.com/imagej/imagej-mesh/blob/2f464f4501c757e0fffc4fc3cb54ce1baba21b4d/src/main/java/net/imagej/mesh/Mesh.java#L86)es have no associated metadata (like a name). Ops themselves generally don't provide meaningful names - you'd usually get a name like `out` or `output`, which I don't see as being better than `Surface`.

So, I have a couple of ideas, but I can't say I'm terribly in favor of any of them:
1. Infer the name from the inputs somehow - we could do something like `binary_blobs - Surface`. Then we'd have to create rules for *which* input is used to infer the name (usually the first, I would guess), etc.
2. Infer the name from the `Module` name - we could do something like `marchingCubes - Surface`. 

Do you have any other ideas? Which do you like best?

**Comment by hinerm** [comment]
@kephale what `isolevel` did you use? I couldn't reproduce your output.

> > Relatedly, is it feasible to have some indicator that the ImageJ call is still running?
> 
> #55 talks about this. I don't have a great idea yet, but I have been thinking about this too.

But #55 is closed; is this not solved? When I ran marching cubes with the activity monitor open, it showed a progress bar until it completed:
![image](https://github.com/imagej/napari-imagej/assets/1123809/a339c882-71f5-4dce-8b12-ba477a27d6e2)

@kephale you can click the "Activity" button at the bottom to get a progress monitor. It will also play a little animation of blue dots while things are in progress, even while minimized.

**Comment by gselzer** [comment]
@hinerm I used `isolevel=1`, and was able to reproduce the output

> But https://github.com/imagej/napari-imagej/issues/55 is closed; is this not solved?

Yeah, the progress stuff is solved. What is not yet solved is what to name the output.

**Comment by hinerm** [comment]
For anyone else wanting to reproduce but unfamiliar with the napari UI, toggle ndisplay mode after running marching cubes to see the full results
![image](https://github.com/imagej/napari-imagej/assets/1123809/476eca23-efe9-45b7-bd77-fa7231d292ba)

**Comment by ctrueden** [comment]
Marching cubes alignment solved by #242. Naming issue tracked separately in #246.
