### ISSUE TITLE
Support nested menu structure

### ISSUE THREAD

**Issue by ctrueden** [imagej/napari-imagej#2]
Right now, all menu items appear directly under _Plugins > napari-imagej_, due to limitations in how the `napari_experimental_provide_function` hook works. We'll need to work with the napari core devs to figure out the best way to render the whole collection of SciJava modules according to their preferred (nested) positions in the menu.

E.g. "Plugins > napari-imagej > Plugins > Debug > System Information" rather than "Plugins > napari-imagej > Plugins Debug System Information"

**Comment by ctrueden** [comment]
With #3, we opted to use a search-bar style interface rather than a nested menu.

**Comment by gselzer** [comment]
Closing this, since we decided not to pursue this direction.
