### ISSUE TITLE
if isinstance(py_value, Collection) returns true for strings

### ISSUE THREAD

**Issue by gselzer** [imagej/napari-imagej#21]
Thanks to @ctrueden for finding this.

The bug is [here](https://github.com/imagej/napari-imagej/blob/186969a077e57477c8f068ba4e36d9dc157adeed/src/napari_imagej/_function.py#L536-L538)

@ctrueden thinks that `ij.py.from_java` is recursive, so we probably don't even need this check.

I blame @elevans for this bug as he told me it wasn't recursive 😜

**Comment by ctrueden** [comment]
I believe it's fixed with 33b7c3a02c7a8263e8ce07f4fb63854be251bf95 (on `ctr-hacking` branch as of this writing).

**Comment by gselzer** [comment]
I'm not sure why this didn't get closed with #33. :man_shrugging:
