### ISSUE TITLE
Add Title to dock widget

### ISSUE THREAD

**Issue by kephale** [imagej/napari-imagej#213]
It looks like there are still some generic widget titles. See "Dock widget 1" in the top right of this screenshot.

<img width="303" alt="image" src="https://github.com/imagej/napari-imagej/assets/400105/4807e6ce-e3e3-48f9-98ed-d25bf3c90ab3">

**Comment by gselzer** [comment]
@kephale I can't seem to reproduce. Can you provide some minimal set of steps?

**Comment by kephale** [comment]
Oh crud sorry, that was me naively doing `viewer.window.add_dock_widget()` without a `name` keyword 😳
