### ISSUE TITLE
double[] gauss ops don't run on sample data

### ISSUE THREAD

**Issue by hinerm** [imagej/napari-imagej#237]
When testing the [Ops use case](https://napari-imagej.readthedocs.io/en/latest/examples/ops.html) I tried running other `filter.gauss` signatures.

When running a signature with an sigma array, it goes to `double[]` (instead of `number` in the single-sigma variants?) and those then do not work on the input test image (embryos). I am assuming this is an issue with type matching..?

![image](https://github.com/imagej/napari-imagej/assets/1123809/fd4901d6-3ba1-4732-8c8a-acec28891b42)

**Comment by gselzer** [comment]
@hinerm what's the error? Are you using enough dimensions in your `sigmas` array? The underlying Op uses one sigma per dimension, so you need the length of the sigma list to be (at least) 3 if you're using the embryos test image

**Comment by hinerm** [comment]
It's unfortunate that there is no indication that a sigma for each dimension is needed - I guess a symptom of exposing the underlying ops directly instead of an abstraction that matches ops to the params.

Also, unfortunate that no feedback is given in the UI that the Op failed.

**Comment by hinerm** [comment]
Essentially duplicated by #234

**Comment by ctrueden** [comment]
@hinerm There is an already an issue for this in the imagej-ops issue tracker: imagej/imagej-ops#646
