### ISSUE TITLE
How to safely use pyimagej and napari-imagej within a Python script

### ISSUE THREAD

**Issue by kephale** [imagej/napari-imagej#243]
As promised in https://github.com/imagej/napari-imagej/issues/241

It looks like there is a threading/non-blocking situation that arises when using pyimagej and napari-imagej within the same script. It seems like napari-imagej is spinning up the JVM in a separate thread[?] and not blocking when the JVM is being launched, as a result the Python evaluation continues and subsequent `jimport` calls cannot work yet.

This script does not work:

```
import napari
from napari_imagej.widgets.napari_imagej import NapariImageJWidget

from napari_imagej import settings

endpoint = "sc.fiji:fiji:2.13.0+org.morphonets:SNT:MANAGED"

settings.imagej_directory_or_endpoint = endpoint

if __name__ == "__main__":

    viewer = napari.Viewer()

    widget = NapariImageJWidget(viewer)

    viewer.window.add_dock_widget(widget)
    
    from scyjava import jimport
    MouseLightLoader = jimport('tracing.io.MouseLightLoader')
```

and gives the following error:

```
Traceback (most recent call last):
  File "<string>", line 17, in __PYTHON_EL_eval
  File "/Users/kharrington/nesoi/examples/napari_imagej_snt.py", line 19, in <module>
    MouseLightLoader = jimport('tracing.io.MouseLightLoader')
  File "/Users/kharrington/mambaforge/envs/nesoi/lib/python3.10/site-packages/scyjava/_java.py", line 405, in jimport
    return jpype.JClass(class_name)
  File "/Users/kharrington/mambaforge/envs/nesoi/lib/python3.10/site-packages/jpype/_jclass.py", line 99, in __new__
    return _jpype._getClass(jc)
TypeError: Class tracing.io.MouseLightLoader is not found
```

and displays 
`Error: Invalid ImageJ2` in the search bar.
which seems to have been triggered by the jpype error above even though it is not exactly an invalid ImageJ2 situation.

**Comment by ctrueden** [comment]
I think the solution is (1). Scripts should demand synchronous initialization of napari-imagej before doing anything else. The jgo bug with test-jar packaging was supposed to have been fixed in commit scijava/jgo@49aa492aa4718608d59f0cbc0d3d7810f6398a5b, included in jgo 1.0.5. Is it possible you are running an older version of jgo?

**Comment by gselzer** [comment]
Ah, okay, thanks for merging that PR @ctrueden. I don't get the jgo bug anymore.

@kephale by adding in the `init_ij` call, and by fixing the `MouseLightLoader` import, the script runs without error for me. What do you think of this? Can you think of a better way to synchronously initialize ImageJ without bricking the napari viewer?

**Comment by kephale** [comment]
> 2\. Do you know if the napari team has talked about asynchronous instantiation of napari widgets, @kephale?

There is discussion about supporting custom initialization code for plugins. The old plugin framework supported it, but it isn't present in npe2 at the moment.

**Comment by gselzer** [comment]
@kephale is there anything else that you'd like done here?

**Comment by kephale** [comment]
Nope, I'm happy, thank you!
