### ISSUE TITLE
Debugging strategy?

### ISSUE THREAD

**Issue by kephale** [imagej/napari-imagej#256]
I'm testing out BoneJ2's Anisotropy  Op, but get an issue with the data that is being passed to BoneJ:

```
[ERROR] Command errored: Anisotropy
java.lang.IllegalArgumentException: Interval must be 3D
	at org.bonej.ops.mil.PlaneParallelLineGenerator.<init>(PlaneParallelLineGenerator.java:94)
	at org.bonej.wrapperPlugins.AnisotropyWrapper.matchOps(AnisotropyWrapper.java:348)
	at org.bonej.wrapperPlugins.AnisotropyWrapper.run(AnisotropyWrapper.java:207)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

I would like to place a breakpoint to be able to inspect the call/action that is being invoked and the corresponding arguments that are being passed. Where is the best place to catch that? I'm looking now and will close this once I find it, but it is taking some time to track through the widgets, actions, etc..

**Comment by gselzer** [comment]
@kephale I'll write out my debugging strategy for napari-imagej. Generally speaking, I find it's easiest to remotely attach onto an existing napari-imagej process.
## Debugging Python issues:
As a VSCode user, I like to use `debugpy`. I start napari using 
```
python -m debugpy --wait-for-client --listen <address>:<port 1> -m napari
```
and then, in VSCode, create a launch configuration to attach to that process, in `launch.json`:
```json
    "configurations": [
        {
            "name": "Python: Remote Attach",
            "type": "python",
            "request": "attach",
            "connect": {
                "host": "<address>",
                "port": <port 1>
            },
            "pathMappings": [
                {
                    "localRoot": "${workspaceFolder}",
                    "remoteRoot": "."
                }
            ],
            "justMyCode": false
        }
    ]
```
That allows you to put breakpoints anywhere in VSCode on the *python* side of napari-imagej

## Debugging Java Issues

For Java issues, I like to do the above, plus the additional steps, which also allow me to remote attach a Java IDE (either IntelliJ or Eclipse).
1. Pass the following command line argument to ImageJ (you can do this in napari-imagej's configuration dialog, and can read more about it [here](https://imagej.net/develop/debugging#attaching-to-imagej-instances)):
```
-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=<port 2>
```
2. Once you restart napari, **and have launched napari-imagej**, you can remote attach from a Java IDE. [Here](https://www.jetbrains.com/help/idea/tutorial-remote-debug.html#625ca036) is how you can do it in IntelliJ - just make sure that you provide `<port 2>` and also select the correct JDK version.

With these steps, you can stop at any breakpoint in Java code.

Let me know if this is what you are looking for, or if I can help in any other way.

**Comment by kephale** [comment]
Cool, thank you!

I'm not using VSCode (emacs instead). I normally use breakpoints throughout my Python code during development and am using ipython + pylsp. 

I found that putting a breakpoint before this call 
https://github.com/imagej/napari-imagej/blob/e6f102348f5b979125573e9b45ca03e5acb462f1/src/napari_imagej/utilities/_module_utils.py#L474C5-L479
was able to get me access to the variables I need to inspect for debugging this type of issue.

**Comment by gselzer** [comment]
Okay, good to know, but the asynchronous execution of the module using the `ModuleService` may give you issues in debugging the `Command` - you might still want to remote attach a Java debugger, in that case. You can definitely still do the Java side of things without using `debugpy`/VSCode!

**Comment by kephale** [comment]
Yes, it seems to not be as straightforward as inspecting the arguments that are passed from Python to Java :P 

I also now realize that one of the values of the debugpy strategy is probably for testing IJ1 code...
