### ISSUE TITLE
Discovering Commands that aren't visible

### ISSUE THREAD

**Issue by kephale** [imagej/napari-imagej#262]
Hi Folks,

I cannot discover some Commands that are declared in SNT, like https://github.com/morphonets/SNT/blob/master/src/main/java/sc/fiji/snt/plugin/SkeletonizerCmd.java

I know we can use the imagej-ops thinning ops, but this is really about testing Commands from SNT. I would point out that this Command is declared with `visible = false` hence the topic title, but I suspect that might be a red herring.

Can someone help me understand why the SkeletonizerCmd won't show up in the napari-imagej search bar with this endpoint:
`endpoint = "sc.fiji:fiji:2.13.0+org.morphonets:SNT:MANAGED"`

Thank you!
Kyle

**Comment by gselzer** [comment]
> Command is declared with `visible = false` hence the topic title, but I suspect that might be a red herring.

@kephale I think that's the opposite of a red herring :laughing:

In [`ModuleSearcher.search`](https://github.com/scijava/scijava-search/blob/1070e28d08e433968da0e9e3a895bc530194ec32/src/main/java/org/scijava/search/module/ModuleSearcher.java#L79), we call `ModuleSearcher.isGoodModule`, and one of the conditions for a "good `Module`" is [that it is visible](https://github.com/scijava/scijava-search/blob/1070e28d08e433968da0e9e3a895bc530194ec32/src/main/java/org/scijava/search/module/ModuleSearcher.java#L167). Furthermore the [Plugin method](https://github.com/scijava/scijava-common/blob/bea8f8c992e4dfc265d3a6bb6d2d2e44168e1a37/src/main/java/org/scijava/plugin/Plugin.java#L151) suggests that when it is true, it *shouldn't* show up in the UI. So I think the behavior is correct here?

**Comment by kephale** [comment]
@gselzer good point. Maybe it would be better to revisit why those aren't visible in SNT!
