### ISSUE TITLE
Consider multiprocessing for ImageJ startup

### ISSUE THREAD

**Issue by gselzer** [imagej/napari-imagej#27]
To start ImageJ, we currently use multithreading ([here](https://github.com/imagej/napari-imagej/blob/929a1051db7473b6e1876b77e9cd61908a8bcfc2/src/napari_imagej/setup_imagej.py#L48)). I'm starting to think that multiprocessing might be the better play. It might also make the lazy initialization of ImageJ easier to handle.

**Comment by gselzer** [comment]
See [this comment](https://github.com/imagej/napari-imagej/pull/11#discussion_r869675881), which motivated this issue.

**Comment by ctrueden** [comment]
I know @hinerm played with multiprocessing with pyimagej in the past, relating to the CellProfiler RunImageJScript implementation. There may be platform issues with it. Also be aware that multiprocessing is spinning new processes, so it's a fundamentally different thing than same-process integration, for which PyImageJ was not originally designed. I have no idea if people use JPype in this way, and if so, how well it works. @hinerm, can you comment a bit on what you know in this direction?

**Comment by Thrameos** [comment]
The JVM is fundamentally limited in such a way that you can't spin it up if there is already a copy and if you fork while there is an existing JVM, the new process will inherit a nonfunctional copy.   I have no idea why this limitation exists (at least in my OS class there wasn't supposed to be difference between the original and the fork), but it makes working with multiprocessing much more difficult.   You either need to spin the forked copies before the JVM is started, or use system to launch a new process with a clean memory so the new process can start its own fresh JVM.   I use such an approach when running the jpype tests if you need a reference.  

Unless there is a strong reason for going to multiprocessing model I would generally avoid it as it means large startup penalties (the JVM is not very slim) and limited memory sharing.   Though for robust data collection systems and other places where individual portions of the software must be independent, fault tolerance, and restartable, multiprocessing can be effective.

**Comment by gselzer** [comment]
Thanks @ctrueden and @Thrameos for the input!

My goal with parallel computing at all here is to avoid blocking napari as a whole while we are spinning up the JVM. It is *not* to do any sort of parallel execution of ImageJ functionality.

> I know @hinerm played with multiprocessing with pyimagej in the past, relating to the CellProfiler RunImageJScript implementation. There may be platform issues with it.

Good to know, if we try it we should be catching these issues with our Github Actions.


> Unless there is a strong reason for going to multiprocessing model I would generally avoid it as it means large startup penalties (the JVM is not very slim) and limited memory sharing. Though for robust data collection systems and other places where individual portions of the software must be independent, fault tolerance, and restartable, multiprocessing can be effective.

@Thrameos the current state is that I initialize the JVM in a new thread to avoid blocking napari during startup. This startup can take a long time (minutes) if the java dependencies have not yet been downloaded by jgo. That new thread sets the imagej gateway to a global variable; all calls to Java functionality then block until the initializing thread terminates (i.e. until that global var has been set). I have not seen any failures locally or in my test suite, nor have I heard of any from others on different platforms (e.g. from @ctrueden)

By switching to a multiprocessing model, we might be able to spin the JVM up faster, avoiding the restrictions of the GIL. At the very least, we could use a `ThreadPool` and use `apply_async` to make the setting of that global variable easier.

This issue is less about actually *making* the change to multiprocessing and more about making the debate happen.

Happy to hear more opinions on this!

**Comment by gselzer** [comment]
> At the very least, we could use a `ThreadPool` and use `apply_async` to make the setting of that global variable easier.

See https://github.com/imagej/napari-imagej/commit/3c0c4ff32b1d13c5aaf6a3eff614b2b0a4fde593 to see how this makes things cleaner.

**Comment by gselzer** [comment]
> This issue is less about actually _making_ the change to multiprocessing and more about making the debate happen.

Well, while I like the idea of multiprocessing, it probably just doesn't worth it.

Firstly, multiprocessing doesn't seem to be [supported on Mac](https://docs.python.org/3/library/multiprocessing.html#introduction)

Secondly, it would seem that java objects cannot be passed between processes. Here's the error I get running my ImageJ initialization code (in function `imagej_init()`):
```python3
# -- PUBLIC API -- #
from multiprocessing import Pool

threadpool = Pool(processes=1)
ij_instance = threadpool.apply_async(func = imagej_init)
```
```
../../../miniconda3/envs/napari-imagej-dev/lib/python3.10/site-packages/_pytest/fixtures.py:1111: in pytest_fixture_setup
    result = call_fixture_func(fixturefunc, request, kwargs)
../../../miniconda3/envs/napari-imagej-dev/lib/python3.10/site-packages/_pytest/fixtures.py:890: in call_fixture_func
    fixture_result = fixturefunc(**kwargs)
tests/conftest.py:13: in ij
    return ij()
src/napari_imagej/setup_imagej.py:59: in ij
    return ij_instance.get()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <multiprocessing.pool.ApplyResult object at 0x7f144a74f3d0>, timeout = None

    def get(self, timeout=None):
        self.wait(timeout)
        if not self.ready():
            raise TimeoutError
        if self._success:
            return self._value
        else:
>           raise self._value
E           multiprocessing.pool.MaybeEncodingError: Error sending result: '<java object 'net.imagej.ImageJ'>'. Reason: 'PicklingError("Can't pickle <java class 'net.imagej.ImageJ'>: attribute lookup net.imagej.ImageJ on imagej failed")'

../../../miniconda3/envs/napari-imagej-dev/lib/python3.10/multiprocessing/pool.py:771: MaybeEncodingError
```

There seem to be issues pickling any Java objects created in the separate process (the same thing happens if I create a process and return a `Double`). I wrote a MCVE below:
```python3
from multiprocessing import Pool
import jpype

def get_a_Double():
    jpype.startJVM(interrupt=True)
    Double = jpype.JClass('java.lang.Double')
    return Double(4)

pool = Pool(1)
j_double = pool.apply_async(get_a_Double)
print(j_double.get())
```
@Thrameos is this a known issue?

**Comment by ctrueden** [comment]
> Firstly, multiprocessing doesn't seem to be [supported on Mac](https://docs.python.org/3/library/multiprocessing.html#introduction)

I read through the docs but not sure where you are getting that idea. It is unclear in the Python docs whether "Unix" includes macOS, since macOS is a *nix system.

> There seem to be issues pickling any Java objects created in the separate process

This is wholly unsurprising, and is what I meant when I said "be aware that multiprocessing is spinning new processes, so it's a fundamentally different thing than same-process integration". Java JNI works when libjvm is loaded as a subprocess, not as a completely separate process (AFAIK). I would be surprised if you could get around the issue with pickling—I would think you need interprocess communication in addition.

> See https://github.com/imagej/napari-imagej/commit/3c0c4ff32b1d13c5aaf6a3eff614b2b0a4fde593 to see how this makes things cleaner.

I'm glad you found a way to improve it! :+1:

**Comment by gselzer** [comment]
> I read through the docs but not sure where you are getting that idea. It is unclear in the Python docs whether "Unix" includes macOS, since macOS is a *nix system.

Hmm, I suppose you are right. My MacOS naivete is showing :sweat_smile:

Regardless, the following works on my Linux machine but does not work on the Mac workstation available to me (macOS Big Sur, Version 11.6.5, Intel Core i7):
```python3
from multiprocessing import Pool

def foo():
    return 4.0

pool = Pool(1)
d = pool.apply_async(foo)
print(d.get())
```

Does this work on your mac @ctrueden?

This [SO post](https://stackoverflow.com/questions/61270799/python-multiprocessing-with-macos) suggests it is a broader issue.

**Comment by ctrueden** [comment]
@gselzer Interesting, thanks for the pointer to the SO post. If you think it's important I can do some testing on my macOS system next week.

**Comment by gselzer** [comment]
> If you think it's important I can do some testing on my macOS system next week.

@ctrueden I don't think it's necessary. I merged https://github.com/imagej/napari-imagej/pull/30 this morning, making the changes from 3c0c4ff. I'm happy to close this issue unless you think multiprocessing still has some value. I am content with leaving this as is, as we have the discussion both here and, with that code, in the PR for posterity.

**Comment by Thrameos** [comment]
There is a JPickler which allows you to send mixed Python/Java pickles.   There issue with the Python pickler does not have the ability to hold state such as the Java serializer.   So we have to create an instance holding the Java portion.   I used the JPickler to send data back and forth between processes.   Usually it reattached the data properly though sometimes shared instances do get split.
