### ISSUE TITLE
napari-imagej widget width grows wider when selecting op search results with long names

### ISSUE THREAD

**Issue by ctrueden** [imagej/napari-imagej#273]
Many op search results have long names. The search results tree takes care to truncate such long names with ellipses. But when selecting one, it replicates the name in a label below, which does not truncate, instead causing the widget to grow in width to accommodate its preferred very wide size.

Expected behavior: the napari-imagej widget should never change width unless the user manually makes it wider. For the name label, we should instead find a way to display too-long names with line wrapping.

**Comment by gselzer** [comment]
Yeah, this is a pesky bug. I'm looking forward to fixing it!
