### ISSUE TITLE
Numeric type inputs have undesirable bounds

### ISSUE THREAD

**Issue by ctrueden** [imagej/napari-imagej#276]
Even for numbers that are not supposed to be bounded, they are hardcoded to [0, 1000) as min/max bounds. For example, the bundled `Example_Script.js` has many numeric inputs of various sizes, but most of them have no explicit min/max declarations, and so should not be bounded. But e.g. the `oLong`, which is a 64-bit signed long type, is still bounded at [0, 1000). If this is an issue with how we are using magic_gui, we should address it, or if it is a fundamental magic_gui limitation/bug, we should file a PR upstream.

**Comment by gselzer** [comment]
Yeah, that's tricky, as we are definitely bounded by magicgui/qt here - that's the default min/max for integer types, iirc.

We could probably start with a function like [this one](https://github.com/imagej/napari-imagej/blob/75cedb62a87a8d8ec20a1669133c517bf48c0b6e/src/napari_imagej/widgets/parameter_widgets.py#L44) to cover `Number`/primitive minima/maxima
