### ISSUE TITLE
Search results should show icons to help disambiguate

### ISSUE THREAD

**Issue by ctrueden** [imagej/napari-imagej#284]
In Fiji, the search results show icons for commands, and in particular all ImageJ 1.x commands use the ImageJ 1.x microscope icon. SciJava commands are able to declare their desired icon, and if they do not due so a stupid puzzle piece icon is used (tangentially: I propose we change all ImageJ2 commands to the IJ2 logo, and all SciJava-layer commands in scijava-plugins-commands to the SciJava logo by default).

In napari-imagej, no icons are shown, and you cannot tell at a glance whether a command is an ImageJ or SciJava/ImageJ2 command. It would be great if napari-imagej could load and display the icons somehow. However, if calling Java to load them as resources out of the JAR files is too expensive time-wise, that would be understandable... but we could at least hardcode in the IJ vs IJ2 icons for each type of command, no?

**Comment by gselzer** [comment]
I started working on this, but I quickly realized that adding icons to a `QTreeWidget` would be tricky, and figured that switching our search results to a Qt model/view approach would probably be the correct fix.

 I started working on this, but I don't have a good enough understanding of the data structure yet...
