### ISSUE TITLE
napari-imagej breaks with Jpype 1.5.1

### ISSUE THREAD

**Issue by hinerm** [imagej/napari-imagej#316]
If I do a napari-imagej install from scratch with `mamba create -n napari-imagej napari-imagej` I currently get `jpype1 1.5.1`.

When starting up `napari-imagej` in this environment, `napari` hard crashes with this message on the command prompt:

![image](https://github.com/user-attachments/assets/38f4f845-a882-420e-bcee-e7c2c00da15c)

Rolling back to `jpype1 1.5.0` works as expected.

**Comment by gselzer** [comment]
This issue isn't specific to napari-imagej, as it can be repeated with a smaller MVCE:
1. Create a conda environment: `mamba env create -n tmp -c conda-forge pyimagej`
2. Run in python: `import imagej; ij = imagej.init()`

This is likely a fix upstream in scyjava?

cc @ctrueden @elevans

**Comment by hinerm** [comment]
@gselzer pointed out this is a reported [issue in Jpype](https://github.com/jpype-project/jpype/issues/1242). It can be reproduced with `import jpype; jpype.startJVM()`.
