### ISSUE TITLE
Handle BOTH ModuleItems in a better way

### ISSUE THREAD

**Issue by ctrueden** [imagej/napari-imagej#42]
When running a SciJava module with a BOTH (i.e. input+output) item, right now, a new layer is created. Instead, napari-imagej should skip creating a layer in favor of refreshing the existing input image layer, since it was mutated inplace.

**Comment by gselzer** [comment]
This is actually a *little* bit tricky. Napari currently [adds a new layer for all outputs](https://github.com/napari/napari/blob/main/docs/guides/magicgui.md#updating-an-existing-layer), unless the name of the output matches an existing layer. The question is then *how* we get that name.

Given the [allowed napari parameter types](https://github.com/napari/napari/blob/main/docs/guides/magicgui.md#parameter-annotations), I'd think we have to take `Layer` subclasses as input. As we currently take `<Layer>Data`s instead, this will require a bit of a change in the type hints. We'd also have to:
* Write a python -> Java converter for `Image` layers, but this would be as simple as:
```python3
converter = new Converter(
  predicate=lambda obj: isinstance(obj, napari.layers.Image),
  converter=lambda obj: ij().py.to_java(obj.data),
  priority=Priority.VERY_HIGH # or whatever we decide the priority should be
)
```
* Add a step to keep track of each `layer.name` and assign it to the output `LayerDataTuple` at the end of execution.

I'll try prototyping this.

**Comment by ctrueden** [comment]
> Napari currently [adds a new layer for all outputs](https://github.com/napari/napari/blob/main/docs/guides/magicgui.md#updating-an-existing-layer)

So just don't emit BOTH parameters as outputs to napari, then? Because it will be updated on the existing layer instead, no?

**Comment by gselzer** [comment]
I thought about it, but it doesn't seem to work. It also relies on the Python->Java conversion being a view.
![image](https://user-images.githubusercontent.com/29754838/170562092-ff71e6e9-902b-4308-b152-f8bab4e7f842.png)

I ran frangi vesselness ([source code](https://github.com/imagej/imagej-ops/blob/9ead9ba0e2ec9604b8c168eb43a9e6162d33f19c/src/main/java/net/imagej/ops/filter/vesselness/DefaultFrangi.java#L61)) with the input being the brick sample, and the output being another instance of that brick sample (brick [1]). brick [1] was not overwritten with the output `out`, which appears to be all zeroes.

**Comment by ctrueden** [comment]
> It also relies on the Python->Java conversion being a view.

Converting an image from Python to Java should always be a view.

> brick [1] was not overwritten with the output out, which appears to be all zeroes.

Yeah, we need to get to the bottom of what's going on here. Mark and I also noticed problems with Frangi vesselness. It wasn't clear to us whether the code was just executing for a long time, or what. I think @hinerm was going to file an issue about potential threading issues along these lines.

**Comment by gselzer** [comment]
> Converting an image from Python to Java should always be a view.

For an image, sure. And actually, images are the *only* layer type whose hint is a `<Layer>Data`, so we shouldn't run into this issue with the other types!

> Yeah, we need to get to the bottom of what's going on here.

Okay, so what is happening is that the output *is* being overwritten, but the layers are not being updated.

![image](https://user-images.githubusercontent.com/29754838/170583568-22c008ba-6e53-406b-b49f-6f284e1d6137.png)

If you then toggle the visibility of `brick [1]`, it updates:

![image](https://user-images.githubusercontent.com/29754838/170583761-6781ea87-923a-42e5-9a5c-99f375c2dde8.png)

So I think you are right, we should just not return mutable arguments. This should be a simple change.

The harder change is figuring out how to update the viewer before we return from our execution. I'll look into that.

**Comment by gselzer** [comment]
> The harder change is figuring out how to update the viewer before we return from our execution. I'll look into that.

Okay, so the napari `Viewer` refreshes its layers using [`_update_layers`](https://github.com/napari/napari/blob/611d5fb3bb4242b6d5e6a6a0aeee93c84e61d9c1/napari/components/viewer_model.py#L318), which we shouldn't use. A more supported way is using `layer.refresh`, which is what that function ends up doing.

So at the end of the day, we *could* write:
```python3
for layer in viewer.layers:
  layer.refresh()
```

This still doesn't seem great, though. I'll ask on zulip about this.

**Comment by ctrueden** [comment]
Why not refresh only the layers which have images that were used as input to BOTH module items?

**Comment by gselzer** [comment]
We cannot know which layer we have without knowing it's name, which we won't have since our input is just an array like. This is why I suggested changing the input type hint for images to the Image layer; then we'd have its name. But if we had the layer anyways, we could just refresh that.

**Comment by ctrueden** [comment]
> We cannot know which layer we have without knowing it's name

You have the references to the image inputs, right? So you can loop over `viewer.layers` and compare the `.data` to the known input image references. Can't you?

**Comment by gselzer** [comment]
Yeah, I did think about that, I just thought it sounded HACKy, and wanted to know if there was a better way. But you are right, we can just do that.
