### ISSUE TITLE
Add a button to pop the ImageJ2 main window when not in headless mode

### ISSUE THREAD

**Issue by ctrueden** [imagej/napari-imagej#43]
So that you can do a bunch of ImageJ stuff at once, in its native UI.

**Comment by ctrueden** [comment]
See also [this thread on Zulip](https://imagesc.zulipchat.com/#narrow/stream/328100-scyjava/topic/Capturing.20ImageJ.20outputs).

**Comment by gselzer** [comment]
This has been done for a while, how did we not close this??

See #89
