### ISSUE TITLE
Consolidate duplicate search results

### ISSUE THREAD

**Issue by hinerm** [imagej/napari-imagej#46]
![reduce-duplicate-signatures](https://user-images.githubusercontent.com/1123809/170524493-7859e579-8aa3-4704-b0b9-3dc46715aeaf.png)

These are indistinguishable, flood the results, and will be confusing to users who see no reason to choose one over the other.

**Comment by ctrueden** [comment]
I wonder if we should expose Ops at all. If we do, we should improve the Ops results to give types on parameters, eh?

**Comment by gselzer** [comment]
> I wonder if we should expose Ops at all.

Ops are going to add a *ton* of functionality. I think we should definitely be including them.

> If we do, we should improve the Ops results to give types on parameters, eh?

I agree, but this change would have to be made in imagej-ops (specifically in `OpSearchResult`)

**Comment by ctrueden** [comment]
I filed imagej/imagej-ops#643 and added it to the napari-imagej project board.

**Comment by gselzer** [comment]
Thanks. This is also a problem in Fiji, so it is great to kill two birds with one stone!
