### ISSUE TITLE
Rename duplicate "Run" buttons

### ISSUE THREAD

**Issue by hinerm** [imagej/napari-imagej#48]
I don't think this button should be called "Run":
![image](https://user-images.githubusercontent.com/1123809/170525556-6380be82-0fa0-475e-ac05-3162287c9388.png)

It's adding a widget for the selected command right? So, let's say something to that effect (with a verbose explanation in a tooltip)

Having two widgets that both contain a "Run" button, where only the latter truly "applies" the plugin results, makes for a confusing user experience.

<s>
In some cases (`math.add(arg, value)` op) I can't tell if it's actually trying to run the op directly? I don't understand how it could without input harvesting. In any case, trying to run the `add` op results in an exception:

If it's trying to run the Op I think it should not, and just always make a widget. If it's trying to make a widget and hitting an exception then that is a separate issue.
</s>
Edit: this was a [separate issue](https://github.com/imagej/napari-imagej/issues/56)

**Comment by gselzer** [comment]
Thanks @hinerm!

I'd think this is a better issue for imagej-ops, as the `Run` action is part of imagej-ops (see [`RunOpSearchActionFactory`](https://github.com/imagej/imagej-ops/blob/9ead9ba0e2ec9604b8c168eb43a9e6162d33f19c/src/main/java/net/imagej/ops/search/RunOpSearchActionFactory.java#L59)). Thus if you search `math.add` in Fiji, you'll see the same behavior, with that `Run` button popping up another widget.

What I will say is that the created  widget in Fiji has a button saying "OK", whereas the napari-imagej button says "Run". We could change the napari-imagej button to match Fiji's?

**Comment by hinerm** [comment]
>What I will say is that the created widget in Fiji has a button saying "OK", whereas the napari-imagej button says "Run". We could change the napari-imagej button to match Fiji's?

The search pane in Fiji has a button called `Run` that actually runs the command. When the Op is run in Fiji, the input harvester creates the dialog with the "ok" button.

Are there any examples of commands that do not create a widget in napari-imagej but just run directly when clicking that first "Run" button that I circled? My expectation when I'm using napari-imagej is that when I click that button it's going to create a widget, and then I'm going to configure my inputs and then run the actual plugin. So I think the button that takes us from search results to widgets should be called something besides "Run". "Create Widget" or "Add Widget" or "Assign Inputs" or something descriptive like that all seem reasonable to me; but just making that the "OK" button to confirm the search result would be acceptable as well. I like that the final button that you click after inputs are assigned is called "Run"

**Comment by gselzer** [comment]
> The search pane in Fiji has a button called `Run` that actually runs the command. When the Op is run in Fiji, the input harvester creates the dialog with the "ok" button.

Sure. This is exactly what happens in napari-imagej, except for the fact that the widget is created by napari-imagej instead of by the input harvester. No?

> Are there any examples of commands that do not create a widget in napari-imagej but just run directly when clicking that first "Run" button that I circled?

Not that I know of, but I don't know much about the wealth of commands.

> So I think the button that takes us from search results to widgets should be called something besides "Run". "Create Widget" or "Add Widget" or "Assign Inputs" or something descriptive like that all seem reasonable to me; but just making that the "OK" button to confirm the search result would be acceptable as well.

Sure. But that would have to be a change made in imagej-ops. I think that napari-imagej's search and run functionality should be as close as possible to Fiji's, which it currently is.

**Comment by ctrueden** [comment]
> Are there any examples of commands that do not create a widget in napari-imagej but just run directly when clicking that first "Run" button that I circled?

One such is Crop. But it's a `no-legacy` command. It relies on a `net.imagej.overlay.Overlay` being attached to the `ImageDisplay`. This is a hairy part of ImageJ2 in that we want to phase it out in favor of imglib2-roi. But if we are going to expose all the no-legacy imagej-plugins-commands, we probably need to support it in napari-imagej in the interim. :sweat: 

> Sure. But that would have to be a change made in imagej-ops. I think that napari-imagej's search and run functionality should be as close as possible to Fiji's, which it currently is.

I don't understand why, for regular commands, the Run button has been overridden to generate a napari dialog via magicgui, but for ops, it has not. This seems inconsistent to me. The Run action is the same for both ops and modules: in fact the `RunOpSearchActionFactory` is just a cut-and-paste of [`RunModuleSearchActionFactory`](https://github.com/scijava/scijava-search/blob/scijava-search-1.0.0/src/main/java/org/scijava/search/module/RunModuleSearchActionFactory.java) from scijava-search. And you aren't proposing we change the code of scijava-search... so what is napari-imagej doing differently here? I think this issue is really about making napari-imagej do the same thing for both plain module and op modules.

**Comment by gselzer** [comment]
> I don't understand why, for regular SciJava modules, the Run button has been overridden to generate a napari dialog via magicgui, but for ops, it has not. This seems inconsistent to me.

It isn't, as far as I can remember. [Here](https://github.com/imagej/napari-imagej/blob/1bba63d449edecc9233eed1e39821a14b2575904/src/napari_imagej/widget.py#L191) is the code that sets up all of the buttons when the user focuses on a module. [This `for` block](https://github.com/imagej/napari-imagej/blob/1bba63d449edecc9233eed1e39821a14b2575904/src/napari_imagej/widget.py#L216) is responsible for creating the button actions. You are right that the `Run` button is overridden, because we have to generate a napari widget for input harvesting, but this code makes no distinction of module type.

> I think this issue is really about making napari-imagej do the same thing for both plain module and op modules.

Sure, my point is that I do not yet see where the module types are being treated differently.

**Comment by gselzer** [comment]
Oh! I understand now.

I tried it for myself, and I got the same error. Here is the traceback:
```
File ~/code/imagej/napari-imagej/src/napari_imagej/widget.py:238, in FocusWidget._execute_module(self=<napari_imagej.widget.FocusWidget object>, moduleInfo=<java object 'org.scijava.command.CommandInfo'>)
    235 module = ij().module().createModule(moduleInfo)
    237 # preprocess using napari GUI
--> 238 func, param_options = functionify_module_execution(
        module = <java object 'org.scijava.command.CommandModule'>
        moduleInfo = <java object 'org.scijava.command.CommandInfo'>
        self.viewer = Viewer(axes=Axes(visible=False, labels=True, colored=True, dashed=False, arrows=True), camera=Camera(center=(0.0, 0.0, 0.0), zoom=1.0, angles=(0.0, 0.0, 90.0), perspective=0, interactive=True), cursor=Cursor(position=(1, 1), scaled=True, size=1, style=<CursorStyle.STANDARD: 'standard'>), dims=Dims(ndim=2, ndisplay=2, last_used=0, range=((0, 2, 1), (0, 2, 1)), current_step=(0, 0), order=(0, 1), axis_labels=('0', '1')), grid=GridCanvas(stride=1, shape=(-1, -1), enabled=False), layers=[], scale_bar=ScaleBar(visible=False, colored=False, ticks=True, position=<Position.BOTTOM_RIGHT: 'bottom_right'>, font_size=10, unit=None), text_overlay=TextOverlay(visible=False, color=(0.5, 0.5, 0.5, 1.0), font_size=10, position=<TextOverlayPosition.TOP_LEFT: 'top_left'>, text=''), overlays=Overlays(interaction_box=InteractionBox(points=None, show=False, show_handle=False, show_vertices=False, selection_box_drag=None, selection_box_final=None, transform_start=<napari.utils.transforms.transforms.Affine object at 0x7fdb0eed29e0>, transform_drag=<napari.utils.transforms.transforms.Affine object at 0x7fdb0eed2a40>, transform_final=<napari.utils.transforms.transforms.Affine object at 0x7fdb0eed2aa0>, transform=<napari.utils.transforms.transforms.Affine object at 0x7fdb0eed2b00>, allow_new_selection=True, selected_vertex=None)), help='', status='Ready', tooltip=Tooltip(visible=False, text=''), theme='dark', title='napari', mouse_move_callbacks=[<function InteractionBoxMouseBindings.initialize_mouse_events.<locals>.mouse_move at 0x7fdb0c179000>], mouse_drag_callbacks=[<function InteractionBoxMouseBindings.initialize_mouse_events.<locals>.mouse_drag at 0x7fdb0c178f70>], mouse_double_click_callbacks=[], mouse_wheel_callbacks=[<function dims_scroll at 0x7fdb0f17f640>], _persisted_mouse_event={}, _mouse_drag_gen={}, _mouse_wheel_gen={}, keymap={'Shift': <function InteractionBoxMouseBindings.initialize_key_events.<locals>.hold_to_lock_aspect_ratio at 0x7fdb0c137880>, 'Control-Shift-R': <function InteractionBoxMouseBindings._reset_active_layer_affine at 0x7fdb0c17a0e0>, 'Control-Shift-A': <function InteractionBoxMouseBindings._transform_active_layer at 0x7fdb0c17a050>})
        self = <napari_imagej.widget.FocusWidget object at 0x7fdaf97eb760>
    239     self.viewer, module, moduleInfo
    240 )
    241 self.viewer.window.add_function_widget(func, magic_kwargs=param_options)

File ~/code/imagej/napari-imagej/src/napari_imagej/_module_utils.py:673, in functionify_module_execution(viewer=Viewer(axes=Axes(visible=False, labels=True, col...ings._transform_active_layer at 0x7fdb0c17a050>}), module=<java object 'org.scijava.command.CommandModule'>, info=<java object 'org.scijava.command.CommandInfo'>)
    670     return layer_outputs
    672 # Add metadata for widget creation
--> 673 _add_napari_metadata(module_execute, info, unresolved_inputs)
        unresolved_inputs = [<java object 'org.scijava.command.CommandModuleItem'>, <java object 'org.scijava.command.CommandModuleItem'>]
        module_execute = <function command:net.imagej.ops.math.ConstantToArrayImageP$AddByte at 0x7fda44610790>
        info = <java object 'org.scijava.command.CommandInfo'>
    674 magic_kwargs = _add_scijava_metadata(
    675     unresolved_inputs, module_execute.__annotation__
    676 )
    678 return (module_execute, magic_kwargs)

File ~/code/imagej/napari-imagej/src/napari_imagej/_module_utils.py:524, in _add_napari_metadata(execute_module=<function command:net.imagej.ops.math.ConstantToArrayImageP$AddByte>, info=<java object 'org.scijava.command.CommandInfo'>, unresolved_inputs=[<java object 'org.scijava.command.CommandModuleItem'>, <java object 'org.scijava.command.CommandModuleItem'>])
    520 _modify_function_signature(execute_module, unresolved_inputs, info)
    522 # Add the type hints as annotations metadata as well.
    523 # Without this, magicgui doesn't pick up on the types.
--> 524 type_hints = {str(i.getName()): python_type_of(i) for i in unresolved_inputs}
        unresolved_inputs = [<java object 'org.scijava.command.CommandModuleItem'>, <java object 'org.scijava.command.CommandModuleItem'>]
    526 type_hints["return"] = _widget_return_type(info)
    528 execute_module._info = info  # type: ignore

File ~/code/imagej/napari-imagej/src/napari_imagej/_module_utils.py:524, in <dictcomp>(.0=<list_iterator object>)
    520 _modify_function_signature(execute_module, unresolved_inputs, info)
    522 # Add the type hints as annotations metadata as well.
    523 # Without this, magicgui doesn't pick up on the types.
--> 524 type_hints = {str(i.getName()): python_type_of(i) for i in unresolved_inputs}
        i = <java object 'org.scijava.command.CommandModuleItem'>
    526 type_hints["return"] = _widget_return_type(info)
    528 execute_module._info = info  # type: ignore

File ~/code/imagej/napari-imagej/src/napari_imagej/_module_utils.py:63, in python_type_of(module_item=<java object 'org.scijava.command.CommandModuleItem'>)
     61     if converted is not None:
     62         return converted
---> 63 raise ValueError(
     64     (
     65         f"Unsupported Java Type: {module_item.getType()}. "
     66         "Let us know about the failure at https://forum.image.sc, "
     67         "or file an issue at https://github.com/imagej/napari-imagej!"
     68     )
     69 )

ValueError: Unsupported Java Type: class net.imglib2.img.array.ArrayImg. Let us know about the failure at https://forum.image.sc, or file an issue at https://github.com/imagej/napari-imagej!
```
The issue is that napari-imagej is unable to create the input harvesting widget for napari, because it cannot determine the type hint for `ArrayImg`. This has nothing to do with ops vs. plain modules, this is simply a bug in the type hint resolution.

That last line is particularly helpful :sweat_smile:

**Comment by hinerm** [comment]
> Sure. But that would have to be a change made in imagej-ops. I think that napari-imagej's search and run functionality should be as close as possible to Fiji's, which it currently is.

The current napari-imagej experience would be akin to something like this in Fiji:
![image](https://user-images.githubusercontent.com/1123809/170737293-5fc569f1-8e4b-4ac1-affa-6c3682d878aa.png)

Where you click the "Run" button, which expands the current panel to present the user with another "Run" button. I conflated this issue in the original post because I didn't know what was happening. I split the `ArrayImg` type hint [to a new issue](https://github.com/imagej/napari-imagej/issues/56) and have refocused this description.

**Comment by gselzer** [comment]
> I conflated this issue in the original post because I didn't know what was happening. I split the `ArrayImg` type hint [to a new issue](https://github.com/imagej/napari-imagej/issues/56) and have refocused this description.

Thanks!

> In Fiji the search box disappears when you run something, and then the input harvesting dialog also disappears.

Yeah, this is a good point.  While the module execution is fundamentally similar, the graphical persistence is different. While I don't think we'd want to make the napari search bar disappear, in a perfect world the input widget would disappear after clicking "Run".

With that being said, I think you've changed my mind on this one @hinerm. We should look into making the input harvesting widget in napari disappear after its' "Run" button is clicked. Unfortunately, I don't know that this is supported; I'd think it should be a parameter to [`Window.add_function_widget()`](https://github.com/napari/napari/blob/9406bf09fb7dc7c44f197cfe94b8362cf0f7b7cb/napari/_qt/qt_main_window.py#L941), but there is nothing there to help us out. We should probably ask on Zulip about this.

> "Create Widget" or "Add Widget" or "Assign Inputs" or something descriptive like that all seem reasonable to me

I'm not a huge fan of any of these, as I don't feel like it conveys well what that widget would do. "Assign Inputs" is my favorite of the 3, but I'd prefer something like "Initialize" or "Start". What do you think?

**Comment by hinerm** [comment]
>We should look into making the input harvesting widget in napari disappear after its "Run" button is clicked.

Personally I think this could wait for broader, general user feedback. Part of me liked having the widget there as a record of what was done and it would be easy to play with different parameters because of the persistence.

>I'm not a huge fan of any of these, as I don't feel like it conveys well what that widget would do. "Assign Inputs" is my favorite of the 3, but I'd prefer something like "Initialize" or "Start". What do you think?

Yup naming is hard. "Initialize", "Go", "OK".. if something feels reasonable-ish then I'd say go with it and it can be changed down the road.
