### ISSUE TITLE
Consider how to handle long-running plugins

### ISSUE THREAD

**Issue by hinerm** [imagej/napari-imagej#55]
Running `Frangi_Vesselness` on the `Embryos` sample image from Fiji takes several seconds on my machine. During that time the napari UI blocks and is unresponsive.

Questions/thoughts:
- Do plugins need to be run on the graphical dispatch thread in napari for any reason?
- Does napari already have a progress/work indicator mechanism?
- Are there any barriers to launching plugins in a separate thread and popping a progress bar?

**Comment by ctrueden** [comment]
Tangentially related: https://forum.image.sc/t/demo-and-proposal-new-progress-bars-for-fiji/64956

**Comment by gselzer** [comment]
These are all good questions @hinerm 
> 
>     * Do plugins need to be run on the graphical dispatch thread in napari for any reason?

Multithreading should be fine, I think? 

>     * Does napari already have a progress/work indicator mechanism?

They [do](https://github.com/napari/napari/blob/640484c10e2db29971130d296729445b52b3e98e/napari/utils/progress.py#L1), but how much of our functionality uses `Task`s? Would it be worth integrating the two?

>     * Are there any barriers to launching plugins in a separate thread and popping a progress bar?

Mostly just my limited knowlege on how ImageJ functionality is currently reporting progress, I think. We could call `module.run()` in a separate thread, I'd think...
