### ISSUE TITLE
Make Widgets.js work, and ship a copy of it for testing

### ISSUE THREAD

**Issue by ctrueden** [imagej/napari-imagej#59]
The [Widgets.js](https://github.com/scijava/scripting-javascript/blob/scripting-javascript-0.5.0/src/main/resources/script_templates/Intro/Widgets.js) script template exercises a lot of parameter types. Let's make sure it fully works in napari-imagej. (Right now, it crashes on the non-integer step size parameter.)

**Comment by gselzer** [comment]
I actually get a crash even earlier:
```
Exception                                 Traceback (most recent call last)
File SaveInputsPreprocessor.java:60, in org.scijava.module.process.SaveInputsPreprocessor.process()

File DefaultModuleService.java:341, in org.scijava.module.DefaultModuleService.saveInputs()

File Collections.java:1085, in java.util.Collections$UnmodifiableCollection.forEach()

File ArrayList.java:1541, in java.util.ArrayList.forEach()

File DefaultModuleService.java:341, in org.scijava.module.DefaultModuleService.lambda$saveInputs$0()

File DefaultModuleService.java:536, in org.scijava.module.DefaultModuleService.saveInput()

File DefaultModuleService.java:303, in org.scijava.module.DefaultModuleService.save()

File DefaultPrefService.java:112, in org.scijava.prefs.DefaultPrefService.put()

File DefaultPrefService.java:390, in org.scijava.prefs.DefaultPrefService$SmartPrefs.put()

File AbstractPreferences.java:257, in java.util.prefs.AbstractPreferences.put()

Exception: Java Exception

The above exception was the direct cause of the following exception:
.
.
.
File ~/code/imagej/napari-imagej/src/napari_imagej/_module_utils.py:649, in functionify_module_execution(viewer=Viewer(axes=Axes(visible=False, labels=True, col...ings._transform_active_layer at 0x7f95005160e0>}), module=<java object 'org.scijava.script.ScriptModule'>, info=<java object 'org.scijava.script.ScriptInfo'>)
    647 """Converts a module into a Widget that can be added to napari."""
    648 # Run preprocessors until we hit input harvesting
--> 649 _preprocess_non_inputs(module)
        module = <java object 'org.scijava.script.ScriptModule'>
    651 # Determine which inputs must be resolved by the user
    652 unresolved_inputs = _filter_unresolved_inputs(module, info.inputs())

File ~/code/imagej/napari-imagej/src/napari_imagej/_module_utils.py:181, in _preprocess_non_inputs(module=<java object 'org.scijava.script.ScriptModule'>)
    179 # we want to avoid these processors
    180 for preprocessor in preprocessors:
--> 181     preprocessor.process(module)
        preprocessor = <java object 'org.scijava.module.process.SaveInputsPreprocessor'>
        module = <java object 'org.scijava.script.ScriptModule'>
```

That `Exception` is coming from [here](https://github.com/scijava/scijava-common/blob/487a40e1fd23246b366396aa26ec0c21c2c42478/src/main/java/org/scijava/module/DefaultModuleService.java#L303), where `item` is `pChar` and `sValue` is an empty string. Then [this line](https://github.com/scijava/scijava-common/blob/487a40e1fd23246b366396aa26ec0c21c2c42478/src/main/java/org/scijava/prefs/DefaultPrefService.java#L112) fails with `IllegalArgumentException: Value contains code point U+0000`.

:frowning:

**Comment by ctrueden** [comment]
Yeah, if I recall correctly, filling in some non-null values for the characters avoids the issue. I'd be happy to discuss the best way to fix this on the SciJava Common side, since I agree the behavior is bad.

**Comment by gselzer** [comment]
> Yeah, if I recall correctly, filling in some non-null values for the characters avoids the issue. I'd be happy to discuss the best way to fix this on the SciJava Common side, since I agree the behavior is bad.

Hmm, can we just implement a conditional in `DefaultConverter`?
