### ISSUE TITLE
Resolve preallocated outputs

### ISSUE THREAD

**Issue by gselzer** [imagej/napari-imagej#6]
There isn't really a good way for us to generate preallocated outputs in napari. napari doesn't really seem to provide an easy way to make a blank image layer, making preallocated image outputs especially tricky.

**Comment by gselzer** [comment]
I agree this would be useful.

I see two different avenues of making a fast way to get a new image:

1. Use another napari plugin. I feel like there has to be a plugin that could create numpy arrays already, but if there isn't, we could write one easily.
2. Write a python script that creates an `UnsafeImg`, which could then be wrapped into a numpy array. We'd have to merge https://github.com/imglib/imglyb/pull/14, but that PR looks ready to go anyways. That python script could then be wrapped into a `ScriptInfo`,  then searchable from the searchbar. 

## Pros of 1.
* Easy to find
* Simpler

## Pros of 2.
* Does not require another module
* Shared data structure avoids jumping the Java <-> Python barrier.

I like 2. better. Opinions @ctrueden @hinerm?

**Comment by ctrueden** [comment]
I would favor option 3: file a PR to napari core that adds a New Image command. It's a super basic thing, which napari really should have built in. It could be modeled after ImageJ's New Image command.

**Comment by gselzer** [comment]
> I would favor option 3: file a PR to napari core that adds a New Image command. It's a super basic thing, which napari really should have built in. It could be modeled after ImageJ's New Image command.

We can ask the napari devs about it, but how would this functionality manifest within napari? As a plugin? It is unprecedented to have any builtin plugins (available from the plugins window), and it would also be a bit strange to add next to the "new layer" buttons in the layers list, as it would require a popup of some sort to declare `data` dimensions. You'd also want to decide on a backing array type in that popup...

**Comment by ctrueden** [comment]
> This would also be a bit unprecedented, as it would require a popup of some sort to declare data dimensions. You'd also want to decide on a backing array type in that popup...

Heh, there are currently *no* other napari menu commands that need to harvest any parameters from the user? That's... super weird! And I'll be shocked if napari can maintain that. Even File &rarr; Open..., which currently opens a dialog box, is eventually going to need some parameters. People will demand it as use cases broaden.

**Comment by ctrueden** [comment]
I started [a topic](https://napari.zulipchat.com/#narrow/stream/212875-general/topic/Creating.20new.20images/near/284064534) on the napari Zulip.

**Comment by gselzer** [comment]
> People will demand it as use cases broaden.

Sure. I personally think that functionality would be useful, I would just want the opinions of the napari devs before trying it, as I don't have a good sense of where that functionality should live.

**Comment by gselzer** [comment]
I believe that this is closed by #64, as we now have an easy way to make a preallocated output.

We can reopen the issue if more functionality is needed.
