### ISSUE TITLE
Persistent vs. Modal Initialization Widgets

### ISSUE THREAD

**Issue by gselzer** [imagej/napari-imagej#66]
There has been a lot of discussion within https://github.com/napari/napari/issues/4579 about whether the parameter harvesting/initialization widgets should be persistent or modal. Let's hash it out in our own issue here.

This discussion was [started](https://github.com/napari/napari/issues/4579#issuecomment-1156805062) by @ctrueden:
> @gselzer I am starting to wonder, now that you have modal dialogs working, whether we should just always use them, in the same way that Fiji does. It is much simpler when hitting enter to run a command in the search bar, to have the dialog pop up, which you can quickly fill in or just press enter again if the settings are already correct, to continue with the execution. Whereas popping the new widget down into the panel clutters things up, as we are discussing here. To what gain? Why do we need this persistent widget with inputs? I prefer modal dialogs.

>If modal dialogs are considered unnaparic (wink) then we can stick with persistent widgets as we have now, but then of course the behavior of napari needs to be better when there are many of them, as discussed here.

The discussion continues after the linked comment.

**Comment by gselzer** [comment]
Replying to the [last comment](https://github.com/napari/napari/issues/4579#issuecomment-1157992833) of the discussion on napari/napari#4579:
> > I hesitate to add more buttons to the SearchActions, it feels like there are so many there already.

> I think it would be fine, if they were all on one line, instead of vertically aligned each on their own line.

Well, here is what it looks like on one line:
![image](https://user-images.githubusercontent.com/29754838/174143490-b7f9fa95-6e08-4593-8555-6948a409b220.png)

Four buttons doesn't look too bad, I can experiment with adding a fifth if you are a fan of this.

> > what do you think about, once napari allows the configuration described https://github.com/imagej/napari-imagej/issues/16#issuecomment-1085789676 , make modality vs. persistence something that the user could configure in the settings?

> Feels like extra work to me. Two buttons is easier to code,

Not sure I agree in the short run, we'd have to add even more ugly case logic into [this function](https://github.com/imagej/napari-imagej/blob/4f6749517002e2c972d3f23ddaeb017a76c26506/src/napari_imagej/widget.py#L204). You're probably right in the long run though.

>  less complex, and gives people instant choice every time (enter vs shift+enter).

I do think that enter vs. shift+enter would be nice, but I think it's also overkill. We are creating two rather different ways of performing the same action.

**Comment by ctrueden** [comment]
BTW, did we ever figure out what happened to the "Javadoc" button?

**Comment by gselzer** [comment]
> I think it's achievable in a general way by using the QT equivalent of FlowLayout, if it has such a thing.

Oh yeah, I forgot about flow layouts. Qt [has one](https://doc.qt.io/qtforpython/examples/example_widgets_layouts_flowlayout.html)

Not sure what happened to the Javadoc button.
