### ISSUE TITLE
Layer outputs not appearing in layer list on Windows

### ISSUE THREAD

**Issue by gselzer** [imagej/napari-imagej#88]
Now that I've finally gotten napari working fine on the LOCI Windows workstation, I have been able to reproduce this bug @JenuC and I noticed yesterday morning.

When we run an operation in napari-imagej (say, `filter.gaussian(image, image, oobf, sigmas`) and run it on example data, the image does not appear in the layer list. This is not something I have seen on Linux, and apparently not something that @ctrueden has noticed on macOS.

Further digging needed.

**Comment by gselzer** [comment]
As an update, I think the fix is already within napari. By taking the following steps I was able to see napari-imagej outputs:
1. Locally cloning the [napari repository](github.com/napari/napari)
2. Navigating to that local repository and installing that napari into my napari-imagej conda environment:
```
conda activate napari-imagej
pip install -e .
```

I then asked @elevans to see if this fix worked on his machine, and he also saw success.

So, my plan to fix this issue is:
1. Wait until napari-imagej>0.4.16 is released (I think they want to jump to 0.5.0)
2. Pin that version as the minimum for napari-imagej.

**Comment by JenuC** [comment]
That worked. The segmentation script runs now and napari gets a label-layer from "net.imglib2.roi.labeling.ImgLabeling". quick question before we close the issue, is there a  current list of imglib2-supported outputs that I can send to napari from the java-side? I tried "net.imglib2.img.Img" and that works 😄

**Comment by gselzer** [comment]
@JenuC there is no formal list; if you think that this is something people would want to use, we should make an issue about it (but this should probably be a feature of PyImageJ more broadly).

Informally, check out [_ptypes.py](https://github.com/imagej/napari-imagej/blob/14ff8151ddbceaf55563041b063a0e765fe4a576/src/napari_imagej/_ptypes.py#L1). There are two classes containing the mappings of Java and Python types. `TypeMappings` should give you an idea of the two-way conversions available between Python and Java. `TypePlaceholders` stores some Python constants that correspond to Java `Enum`s.

**Comment by gselzer** [comment]
> So, my plan to fix this issue is:

> 1. Wait until napari>0.4.16 is released (I think they want to jump to 0.5.0)
> 2. Pin that version as the minimum for napari-imagej.


Looks like napari released 0.4.17 *last month*, I'll test this today.
