### ISSUE TITLE
Improve data transfer button icons

### ISSUE THREAD

**Issue by gselzer** [imagej/napari-imagej#91]
The new GUI buttons could use a visual overhaul to better convey functionality. Since we are talking about importing/exporting data to/from ImageJ2, we can maybe use classic import/export icons.

The main barrier here is getting SVGs that display correctly. @elevans tried this quickly, but they rendered strangely on my machine.

![image](https://user-images.githubusercontent.com/29754838/184905961-0f6a33ee-b259-497f-b4f4-035e1f43b076.png)

We also want them to recolor correctly. @tlambert03 do you have any suggestions here? How were the napari icons made?

**Comment by ctrueden** [comment]
If you peek into the source code of the SVGs (it's just XML), you can probably figure out what's different.

**Comment by gselzer** [comment]
> If you peek into the source code of the SVGs (it's just XML), you can probably figure out what's different.

:+1:

Yes, things look just fine using a stock napari icon.

Here's a preview of the gif I'm adding to the `README` documenting this:
![napari_imagej_gui_and_data_transfer](https://user-images.githubusercontent.com/29754838/184916245-0dfbd2a2-776e-46c9-9255-9b168dd6843d.gif)
