### ISSUE TITLE
Allow scripts folder directory configuration

### ISSUE THREAD

**Issue by gselzer** [imagej/napari-imagej#92]
In #89 we created a `settings.yml` (which will eventually be replaced by napari's configuration endpoint) for storing user preferences. One of these preferences should be the location of the scripts directory.

**Comment by ctrueden** [comment]
I would advise keeping it simple here and making a single directory that is the user's napari config folder, which should conform to OS conventions. So e.g. on Linux and macOS, `~/.config/napari-imagej`, and on Windows some horrible `%HOMEPATH%\AppData\Local` subfolder. Or perhaps piggybacking off of some existing napari config folder like `~/.config/napari/imagej` if napari already uses e.g. `~/.config/napari` and provides API to discern where this location would be.

And then in that single config folder, you can have the `settings.yml`, and the `scripts` folder.

And then if the user wants to override where to find the `settings.yml` itself, they need to set an environment variable like `NAPARI_IMAGEJ_CONFIG`. This is how most other programs do it.

**Comment by gselzer** [comment]
Yeah, maybe. I also want to look into [dynaconf](https://www.dynaconf.com/).

I do hestitate to do all this work, though, as the end goal is to really just be using napari's configuration endpoints in `napari.yml`. I think that's pretty close, right @tlambert03?

**Comment by ctrueden** [comment]
> I do hestitate to do all this work, though, as the end goal is to really just be using napari's configuration endpoints

Yeah, agreed that we should do this later, if at all. I moved it to 1.0.0, because we should have a stable config solution in place for the stable release. But in the meantime, it's fine to just check the CWD for both `napari.yml` and the `scripts` folder. The advantage of using CWD is that the user can control it easily.

**Comment by tlambert03** [comment]
> I do hestitate to do all this work, though, as the end goal is to really just be using napari's configuration endpoints in napari.yml. I think that's pretty close, right @tlambert03?

yeah, that's a bit of a tough call.  The schema is in place for npe2 configuration contributions, but there's a decent amount of implementation and validation left to be done before its robust.  If you guys have relatively extensive configuration needs (and I can imagine you would), I would not fault you at all for looking into your own internal system for now, so we're not holding you back.  I'm happy to help make an "adapter" to any existing config system you might have once we roll out full support for (re)storing configuration for plugins

**Comment by gselzer** [comment]
@ctrueden would you consider this fixed? Here's the current state. 
* When you start napari-imagej, the application's base directory is set to the default in `config-default.yaml`, which is the current working directory. Under the hood, napari-imagej will replace the `.` in the settings with your absolute path.
* You can configure the ImageJ base directory in the napari-imagej settings dialog, *but* napari-imagej will only write out your choices if you make a changes, making your own config file if necessary.

So, if you want to fix your imagej base directory *to some particular directory* `foo/bar`, you have to start napari from some *other* directory, open the configuration and set your base directory to `foo/bar`, and then that will save for later. If you try to set the base directory from the same directory you want to set, napari-imagej will say "since you didn't change the directory from the default (i.e. the current directory), I'm not going to write out any settings" and you won't have configured the directory.

I feel like this could be done better, but I don't know how. *Should* we just always write the first directory you launch napari-imagej from as the user's configured imagej base directory? Is there a common best practice here?

**Comment by ctrueden** [comment]
As of #226, I am happy with the state of the settings logic's `imagej_base_directory`, which defaults to `.` but can be changed as desired.
