### ISSUE TITLE
Re-enable imagej functionality after disposal

### ISSUE THREAD

**Issue by gselzer** [imagej/napari-imagej#93]
If the ImageJ2 Gateway is disposed of, we lose all ImageJ2 functionality. This happens currently whenever you launch and then close the ImageJ GUI.

@ctrueden suggested a fix of  checking the state of the context in `setup_imagej.ij()`, and restarting the Gateway if it was disposed. 

When this issue is fixed, we need to also update the documentation.

**Comment by ctrueden** [comment]
Better would be, when the ImageJ main window is closed, to *not* dispose the context. Then users can just bring back the main window again by clicking the button, and it'll have all the same state it had before, which I think better respects PoLA.

**Comment by gselzer** [comment]
> Along with this, I would also suggest that when the ImageJ main window is closed, to _not_ dispose the context. Then users can just bring back the main window again by clicking the button, and it'll have all the same state it had before, which I think better respects PoLA.

@ctrueden yeah, this would be ideal. I just don't know how we do that, at least with the ImageJ `LegacyUI` we are using currently. (I also don't know how you do it with the ImageJ2 GUI, but I assume it is easier?)

**Comment by ctrueden** [comment]
```java
import java.awt.Window;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;

import javax.swing.JButton;
import javax.swing.JFrame;

import net.imagej.ImageJ;

import org.scijava.ui.ApplicationFrame;
import org.scijava.widget.UIComponent;

public class NeverGiveUp {
	public static void killWindowListeners(Window w) {
		for (WindowListener l : w.getWindowListeners()) {
			w.removeWindowListener(l);
		}
		w.addWindowListener(new WindowAdapter() {
			@Override
			public void windowClosing(WindowEvent e) {
				w.setVisible(false);
			}
		});
	}

	public static void main(final String... args) {
		System.out.println("Booting ImageJ");
		final ImageJ ij = new ImageJ();

		System.out.println("Configuring controls");
		final JFrame f = new JFrame("ImageJ controls");
		final JButton showUI = new JButton("Show UI");
		showUI.addActionListener(e -> ij.ui().showUI());
		f.getContentPane().add(showUI);
		f.pack();
		f.setVisible(true);

		System.out.println("Killing ImageJ's window listeners");
		ApplicationFrame appFrame = ij.ui().getDefaultUI().getApplicationFrame();
		if (appFrame instanceof Window) {
			killWindowListeners((Window) appFrame);
		}
		if (appFrame instanceof UIComponent) {
			Object component = ((UIComponent<?>) appFrame).getComponent();
			if (component instanceof Window) {
				killWindowListeners((Window) component);
			}
		}
	}
}
```

**Comment by ctrueden** [comment]
Thinking about this briefly again now: I don't think we *need* to make the explicit Quit functions not dispose the context. If you Quit, then you dispose the context, and napari-imagej can handle spinning up a new one as needed, as per this issue. But if you just press the X, it can (using something similar to the above code) just hide the window instead of disposing. This seems like a nice balance to me.
