### ISSUE TITLE
Allow ImageJ Legacy inclusion as a configurable setting

### ISSUE THREAD

**Issue by gselzer** [imagej/napari-imagej#94]
Adding this will be easy. Testing it will be harder.

**Comment by gselzer** [comment]
As a part of this, let's also add some way to conditionally import ImageJ Legacy classes within `types/mappings.py`.

As per [this comment](https://github.com/imagej/napari-imagej/pull/95#discussion_r959868905), we have a `TODO` to add in these imports when we are running with legacy.

**Comment by ctrueden** [comment]
@gselzer Since your last comment above, you made `add_legacy` configurable by the user... can the linked `TODO` comment be removed, and this issue closed as completed?

**Comment by gselzer** [comment]
@ctrueden I left it open due to [this comment](https://github.com/imagej/napari-imagej/issues/94#issuecomment-1234371372).

#121, when merged, is set to close this issue.
